name: HungerGames
author: Eric Dupont
version: 1.0
main: de.hg.main.main
commands:
     money:
          description: Check how much money you got
     world:
          description: Just a test command
     hub:
          description: Join the lobby server
     admin:
          description: A Admin Command to join the adminmode
     gamemode:
          description: This is to change you gamemode
     heal:
          description: This Command is to heal yourself or other player
     bug: 
          description: A Command to report bugs!