name: HungerGames
author: Eric Dupont
version: 1.0
main: de.hg.main.main
commands:
     start:
          description: You can start the game directly
     ping:
          description: Check your ping to the server